import VFH2.UnrestrictedBridge.ProductFiniteObservationCompleteness
import VFH2.Product.ProductRestrictedParamsLedgerEffectProofSpineCharacterization
import VFH2.Product.ProductTrajectoryStationarity

/-!
# Product Finite-Observation Dynamic Proof-Spine Conservativity

This module gives the first direct all-time semantic transport from an
admissible countably indexed `StateU` observation to the current restricted
Product proof spine. It defines the genuine trajectory obtained by repeatedly
applying `updateU` and constructs the unique typed Product representative whose
embedded Product trajectory agrees with it at every time on the complete
canonical Product window.

For that representative, the finite-window ledger effect is preserved exactly,
and the concrete zero-ledger-effect restricted proof-spine target is equivalent
at every time both to fixedness of the countable trajectory state and to the
exact temporal classification "initially fixed or positive time".

Boundary:
- Agreement and uniqueness concern only the canonical finite Product window.
  The unobserved infinite tail is neither reconstructed nor equated.
- The countable update is the existing coordinatewise `updateU`; no global
  infinite ledger or new score is introduced.
- The proof-spine statement uses the existing Product ledger effect and exact
  score window `[0, 0]`, not an arbitrary threshold.
- This is a finite-observation conservativity theorem, not unrestricted
  `TTP-VF-H2-004` and not full-theory, empirical, physical, or biological
  validation.
- No new assumption is introduced.
-/

namespace VFH2
namespace UnrestrictedBridge

/-- The discrete countably indexed trajectory generated by repeated `updateU`. -/
def updateUTrajectory
    (p : ParamsU)
    (x : StateU) :
    Nat → StateU
  | 0 => x
  | t + 1 => updateU p (updateUTrajectory p x t)

private theorem stateUOfProduct_productUpdateTrajectory
    (p : ProductRestrictedParams)
    (y : p.State)
    (t : Nat) :
    stateUOfProduct p (productUpdateTrajectory p y t) =
      updateUTrajectory
        (paramsUOfProduct p)
        (stateUOfProduct p y)
        t := by
  induction t with
  | zero =>
      rfl
  | succ t ih =>
      rw [productUpdateTrajectory_succ]
      rw [stateUOfProduct_productUpdateState]
      simp only [updateUTrajectory]
      rw [ih]

private theorem updateUTrajectory_eq_on_window_of_eq_on_window
    (q : ParamsU)
    (window : List Nat)
    (x z : StateU)
    (hObserved :
      ∀ i : Nat,
        i ∈ window → x i = z i) :
    ∀ t i : Nat,
      i ∈ window →
        updateUTrajectory q x t i =
          updateUTrajectory q z t i := by
  intro t
  induction t with
  | zero =>
      exact hObserved
  | succ t ih =>
      intro i hi
      by_cases ha : i ∈ q.active
      · simp [updateUTrajectory, updateU, ha]
      · simp [updateUTrajectory, updateU, ha, ih i hi]

/--
Every admissible countably indexed state has exactly one typed Product state
whose complete Product trajectory represents its repeated `updateU` trajectory
on the canonical finite window. The representative preserves the observed
ledger effect, and its restricted proof-spine target has the same exact
fixedness and time classification as the countable trajectory.

The final equivalence is the uniqueness assertion: a Product state represents
the whole observed countable trajectory if and only if it is the constructed
representative.
-/
theorem existsUnique_productState_finiteObservationDynamicProofSpineRepresentative
    (p : ProductRestrictedParams)
    (x : StateU)
    (hx : inStateSpaceU (paramsUOfProduct p) x) :
    ∃ y : p.State,
      productLedgerEffect p y =
          ledgerEffectOn
            (paramsUOfProduct p)
            (productWindowU p)
            x ∧
      (∀ t : Nat,
        (ProductRestrictedParamsRestrictedProofSpineFreeze.restrictedProofSpineTarget
              p
              (productUpdateTrajectory p y t)
              (productUpdateState p)
              (productLedgerEffect p)
              (ProductRestrictedParamsCanonicalRawEqualities.canonicalRestrictedTypedUpdate
                p
                (productUpdateTrajectory p y t)
                (productUpdateState p))
              (ProductRestrictedParamsCanonicalRawEqualities.canonicalRestrictedTypedScore
                p
                (productUpdateTrajectory p y t)
                (productUpdateState p)
                (productLedgerEffect p))
              (ProductFixedSet p (productUpdateTrajectory p y t))
              0
              0
              (Int.le_refl 0)
            ↔
          inFixedSetU
              (paramsUOfProduct p)
              (updateUTrajectory (paramsUOfProduct p) x t)) ∧
        (inFixedSetU
              (paramsUOfProduct p)
              (updateUTrajectory (paramsUOfProduct p) x t)
            ↔
          inFixedSetU (paramsUOfProduct p) x ∨ 0 < t)) ∧
      ∀ z : p.State,
        ((∀ t i : Nat,
            i ∈ productWindowU p →
              stateUOfProduct p (productUpdateTrajectory p z t) i =
                updateUTrajectory (paramsUOfProduct p) x t i) ↔
          z = y) := by
  obtain ⟨y, hyWindow, hyEffect, hyUnique⟩ :=
    exists_productState_finiteObservationRepresentative p x hx

  have hyTrajectory :
      ∀ t i : Nat,
        i ∈ productWindowU p →
          stateUOfProduct p (productUpdateTrajectory p y t) i =
            updateUTrajectory (paramsUOfProduct p) x t i := by
    intro t i hi
    rw [stateUOfProduct_productUpdateTrajectory]
    exact
      updateUTrajectory_eq_on_window_of_eq_on_window
        (paramsUOfProduct p)
        (productWindowU p)
        (stateUOfProduct p y)
        x
        hyWindow
        t
        i
        hi

  have hInitialFixed :
      ProductFixedSet p y ↔
        inFixedSetU (paramsUOfProduct p) x := by
    calc
      ProductFixedSet p y ↔ productLedgerEffect p y = 0 :=
        (productLedgerEffect_eq_zero_iff_productFixedSet p y).symm
      _ ↔ ledgerEffectOn
              (paramsUOfProduct p)
              (productWindowU p)
              x = 0 := by rw [hyEffect]
      _ ↔ inFixedSetU (paramsUOfProduct p) x :=
        ledgerEffectOn_eq_zero_iff_inFixedSetU
          (paramsUOfProduct p)
          (productWindowU p)
          x
          hx
          (productWindowU_covers_active p)

  have hCountableFixed :
      ∀ t : Nat,
        inFixedSetU
              (paramsUOfProduct p)
              (updateUTrajectory (paramsUOfProduct p) x t)
          ↔
        inFixedSetU (paramsUOfProduct p) x ∨ 0 < t := by
    intro t
    cases t with
    | zero =>
        simp [updateUTrajectory]
    | succ t =>
        simp only [updateUTrajectory]
        constructor
        · intro _
          exact Or.inr (Nat.succ_pos t)
        · intro _
          exact updateU_inFixedSetU _ _

  have hyProofSpine :
      ∀ t : Nat,
        (ProductRestrictedParamsRestrictedProofSpineFreeze.restrictedProofSpineTarget
              p
              (productUpdateTrajectory p y t)
              (productUpdateState p)
              (productLedgerEffect p)
              (ProductRestrictedParamsCanonicalRawEqualities.canonicalRestrictedTypedUpdate
                p
                (productUpdateTrajectory p y t)
                (productUpdateState p))
              (ProductRestrictedParamsCanonicalRawEqualities.canonicalRestrictedTypedScore
                p
                (productUpdateTrajectory p y t)
                (productUpdateState p)
                (productLedgerEffect p))
              (ProductFixedSet p (productUpdateTrajectory p y t))
              0
              0
              (Int.le_refl 0)
            ↔
          inFixedSetU
              (paramsUOfProduct p)
              (updateUTrajectory (paramsUOfProduct p) x t)) ∧
        (inFixedSetU
              (paramsUOfProduct p)
              (updateUTrajectory (paramsUOfProduct p) x t)
            ↔
          inFixedSetU (paramsUOfProduct p) x ∨ 0 < t) := by
    intro t
    refine ⟨?_, hCountableFixed t⟩
    rw [hCountableFixed t]
    rw [← hInitialFixed]
    rw [← productTrajectoryStationaryFrom_iff_initialFixed_or_pos]
    rw [productTrajectoryStationaryFrom_iff_fixedAt]
    exact
      ProductRestrictedParamsLedgerEffectProofSpineCharacterization.restrictedParams_productLedgerEffect_proofSpineTarget_iff_productFixedSet
        p
        (productUpdateTrajectory p y t)

  refine ⟨y, hyEffect, hyProofSpine, ?_⟩
  intro z
  constructor
  · intro hzTrajectory
    apply hyUnique z
    intro i hi
    have hAtZero := hzTrajectory 0 i hi
    simpa [updateUTrajectory] using hAtZero
  · intro hz
    subst z
    exact hyTrajectory

end UnrestrictedBridge
end VFH2
