import VFH2.Product.ProductOfficialRestrictedBridgeLedgerStateSpaceEquivalence
import VFH2.Product.ProductOfficialRestrictedBridgeOneStepStabilization
import VFH2.Product.ProductFiniteTimeStabilization

/-!
# Product/Official Restricted-Bridge Well-Formed Dynamical Equivalence

The canonical Product decoder for arbitrary official well-formed parameters
commutes with the official restricted update.  The resulting conjugacy is
extended from one step to the entire discrete trajectory.  Thus inverse
dynamical transport is no longer limited to official parameters already
presented as a canonical Product serialization or to a single transition.

Boundary:
- This connects only the two current restricted formalizations.
- It is not unrestricted `TTP-VF-H2-004`.
- It is not full-theory, empirical, or biological validation.
- The trajectory below only iterates the existing official restricted update;
  it introduces no new update, assumption, ledger semantics, compatibility API,
  or workflow.
- It makes no claim about raw lists outside the official restricted state
  space.
-/

namespace VFH2
namespace ProductOfficialRestrictedBridgeWellFormedDynamicalEquivalence

open ProductOfficialRestrictedBridgeStateTransport
open ProductOfficialRestrictedBridgeDynamicsTransport
open ProductOfficialRestrictedBridgeTransitionReflection
open ProductOfficialRestrictedBridgeStateSpaceEquivalence
open ProductOfficialRestrictedBridgeParameterSpaceEquivalence
open ProductOfficialRestrictedBridgeLedgerStateSpaceEquivalence

private theorem officialRestrictedParams_productParamsOfOfficialWellFormed_eq_params
    (wp : RestrictedBridge.WellFormedRestrictedParams) :
    officialRestrictedParams
        (productParamsOfOfficialWellFormed wp) =
      wp.params := by
  exact congrArg
    RestrictedBridge.WellFormedRestrictedParams.params
    (officialWellFormedRestrictedParams_productParamsOfOfficialWellFormed wp)

/--
For every official well-formed parameter object and every state in its
restricted state space, decoding after the official update equals updating
after the canonical Product decode.
-/
theorem productStateOfOfficialWellFormedState_updateStateR
    (wp : RestrictedBridge.WellFormedRestrictedParams)
    (y : RestrictedBridge.State)
    (hspace :
      RestrictedBridge.inRestrictedStateSpace wp.params y) :
    productStateOfOfficialWellFormedState
        wp
        (RestrictedBridge.updateStateR wp.params y)
        (RestrictedBridge.updateStateR_preserves_inRestrictedStateSpace
          hspace) =
      productUpdateState
        (productParamsOfOfficialWellFormed wp)
        (productStateOfOfficialWellFormedState wp y hspace) := by
  let p := productParamsOfOfficialWellFormed wp
  have hParams :
      officialRestrictedParams p = wp.params :=
    officialRestrictedParams_productParamsOfOfficialWellFormed_eq_params wp
  apply officialRestrictedState_injective p
  change
    officialRestrictedState p
        (productStateOfOfficialRestrictedState
          p
          (RestrictedBridge.updateStateR wp.params y)
          _) =
      officialRestrictedState p
        (productUpdateState p
          (productStateOfOfficialRestrictedState p y _))
  rw [officialRestrictedState_productStateOfOfficialRestrictedState]
  rw [officialRestrictedState_productUpdateState_eq_updateStateR]
  rw [officialRestrictedState_productStateOfOfficialRestrictedState]
  rw [hParams]

/--
The discrete official trajectory generated by repeatedly applying the existing
restricted update to a state.
-/
def officialWellFormedUpdateTrajectory
    (wp : RestrictedBridge.WellFormedRestrictedParams)
    (y : RestrictedBridge.State) :
    Nat → RestrictedBridge.State
  | 0 => y
  | k + 1 =>
      RestrictedBridge.updateStateR
        wp.params
        (officialWellFormedUpdateTrajectory wp y k)

/--
Every time slice of an official trajectory starting in the restricted state
space remains in that state space.
-/
theorem officialWellFormedUpdateTrajectory_inRestrictedStateSpace
    (wp : RestrictedBridge.WellFormedRestrictedParams)
    (y : RestrictedBridge.State)
    (hspace :
      RestrictedBridge.inRestrictedStateSpace wp.params y)
    (t : Nat) :
    RestrictedBridge.inRestrictedStateSpace
      wp.params
      (officialWellFormedUpdateTrajectory wp y t) := by
  induction t with
  | zero =>
      exact hspace
  | succ k ih =>
      exact
        RestrictedBridge.updateStateR_preserves_inRestrictedStateSpace ih

/--
At every discrete time, canonically decoding the official trajectory gives
exactly the Product trajectory of the canonically decoded initial state.
-/
theorem productStateOfOfficialWellFormedState_trajectory
    (wp : RestrictedBridge.WellFormedRestrictedParams)
    (y : RestrictedBridge.State)
    (hspace :
      RestrictedBridge.inRestrictedStateSpace wp.params y)
    (t : Nat) :
    productStateOfOfficialWellFormedState
        wp
        (officialWellFormedUpdateTrajectory wp y t)
        (officialWellFormedUpdateTrajectory_inRestrictedStateSpace
          wp y hspace t) =
      productUpdateTrajectory
        (productParamsOfOfficialWellFormed wp)
        (productStateOfOfficialWellFormedState wp y hspace)
        t := by
  induction t with
  | zero =>
      rfl
  | succ k ih =>
      change
        productStateOfOfficialWellFormedState
            wp
            (RestrictedBridge.updateStateR
              wp.params
              (officialWellFormedUpdateTrajectory wp y k))
            _ =
          productUpdateState
            (productParamsOfOfficialWellFormed wp)
            (productUpdateTrajectory
              (productParamsOfOfficialWellFormed wp)
              (productStateOfOfficialWellFormedState wp y hspace)
              k)
      rw [
        productStateOfOfficialWellFormedState_updateStateR
          wp
          (officialWellFormedUpdateTrajectory wp y k)
          (officialWellFormedUpdateTrajectory_inRestrictedStateSpace
            wp y hspace k)
      ]
      rw [ih]

end ProductOfficialRestrictedBridgeWellFormedDynamicalEquivalence
end VFH2
