import VFH2.Product.ProductFixedPointCharacterization

/-!
# VF-H2 Restricted Product Finite-Time Stabilization

This file gives the complete discrete-time trajectory semantics of the current
restricted product update.

Scientific result:
- Time zero is the supplied initial state.
- Every positive time equals the state produced by the first update.
- Hence the trajectory is constant after time one.
- Every positive-time state is fixed.
- Every positive-time ledger effect is zero.
- A nonfixed initial state differs from every positive-time state.

This is stronger than a one-step idempotence statement because it characterizes
the whole finite-time orbit.

Boundary:
- The result is only for `ProductRestrictedParams` and `productUpdateState`.
- It proves that this restricted update has no nontrivial dynamics after its
  first step.
- It does not prove unrestricted TTP-VF-H2-004 or the full Viruse Fabric theory.
- It is not empirical or biological validation.
-/

namespace VFH2

/--
Discrete trajectory generated by repeated restricted product updates.
-/
def productUpdateTrajectory
    (p : ProductRestrictedParams)
    (x : p.State) :
    Nat → p.State
  | 0 => x
  | k + 1 =>
      productUpdateState p (productUpdateTrajectory p x k)

@[simp] theorem productUpdateTrajectory_zero
    (p : ProductRestrictedParams)
    (x : p.State) :
    productUpdateTrajectory p x 0 = x := by
  rfl

@[simp] theorem productUpdateTrajectory_succ
    (p : ProductRestrictedParams)
    (x : p.State)
    (k : Nat) :
    productUpdateTrajectory p x (k + 1) =
      productUpdateState p (productUpdateTrajectory p x k) := by
  rfl

/--
Every positive trajectory time equals the concrete state produced by the first
update.
-/
theorem productUpdateTrajectory_succ_eq_one_step
    (p : ProductRestrictedParams)
    (x : p.State)
    (k : Nat) :
    productUpdateTrajectory p x (k + 1) =
      productUpdateState p x := by
  induction k with
  | zero =>
      rfl
  | succ k ih =>
      rw [productUpdateTrajectory_succ]
      rw [ih]
      exact productUpdateState_idempotent p x

/--
A trajectory at any positive time is exactly its one-step state.
-/
theorem productUpdateTrajectory_eq_one_step_of_pos
    (p : ProductRestrictedParams)
    (x : p.State)
    (t : Nat)
    (ht : 0 < t) :
    productUpdateTrajectory p x t =
      productUpdateState p x := by
  cases t with
  | zero =>
      exact (Nat.not_lt_zero 0 ht).elim
  | succ k =>
      simpa only [Nat.succ_eq_add_one] using
        productUpdateTrajectory_succ_eq_one_step p x k

/--
The restricted orbit is constant at all positive times.
-/
theorem productUpdateTrajectory_eq_of_pos
    (p : ProductRestrictedParams)
    (x : p.State)
    (s t : Nat)
    (hs : 0 < s)
    (ht : 0 < t) :
    productUpdateTrajectory p x s =
      productUpdateTrajectory p x t := by
  rw [
    productUpdateTrajectory_eq_one_step_of_pos p x s hs,
    productUpdateTrajectory_eq_one_step_of_pos p x t ht
  ]

/--
Every positive-time trajectory state belongs to the product fixed set.
-/
theorem productUpdateTrajectory_ProductFixedSet_of_pos
    (p : ProductRestrictedParams)
    (x : p.State)
    (t : Nat)
    (ht : 0 < t) :
    ProductFixedSet p (productUpdateTrajectory p x t) := by
  rw [productUpdateTrajectory_eq_one_step_of_pos p x t ht]
  exact productUpdateState_ProductFixedSet p x

/--
Every positive-time trajectory state has zero product ledger effect.
-/
theorem productUpdateTrajectory_ledgerEffect_zero_of_pos
    (p : ProductRestrictedParams)
    (x : p.State)
    (t : Nat)
    (ht : 0 < t) :
    productLedgerEffect p (productUpdateTrajectory p x t) = 0 := by
  rw [productUpdateTrajectory_eq_one_step_of_pos p x t ht]
  exact productLedgerEffect_after_update_zero p x

/--
If the initial state is already fixed, the complete trajectory is constant from
time zero.
-/
theorem productUpdateTrajectory_eq_initial_of_fixed
    (p : ProductRestrictedParams)
    (x : p.State)
    (hFixed : ProductFixedSet p x)
    (t : Nat) :
    productUpdateTrajectory p x t = x := by
  cases t with
  | zero =>
      rfl
  | succ k =>
      rw [
        productUpdateTrajectory_eq_one_step_of_pos
          p x (Nat.succ k) (Nat.succ_pos k)
      ]
      exact
        (productFixedSet_iff_productUpdateState_eq_self p x).mp hFixed

/--
If the initial state is nonfixed, time zero differs from every positive-time
state. Thus the restricted stabilization time is exactly one.
-/
theorem productUpdateTrajectory_zero_ne_of_not_fixed_and_pos
    (p : ProductRestrictedParams)
    (x : p.State)
    (hNotFixed : ¬ ProductFixedSet p x)
    (t : Nat)
    (ht : 0 < t) :
    productUpdateTrajectory p x 0 ≠
      productUpdateTrajectory p x t := by
  rw [
    productUpdateTrajectory_zero,
    productUpdateTrajectory_eq_one_step_of_pos p x t ht
  ]

  intro hEq

  apply hNotFixed

  exact
    (productFixedSet_iff_productUpdateState_eq_self p x).mpr hEq.symm

end VFH2
