import VFH2.Product.ThreeTimeChainRepresentabilityCharacterization

/-!
# C133: Three-Time Causal Semantic Recovery

This module restores a minimal causal semantics on top of the verified
three-time relational geometry:

* an ordered deterministic structural model with explicit downstream laws;
* surgical present/future interventions and no-retrocausality;
* evidence-relative candidate pasts and strict observer recontextualization;
* a computable rectangle defect equivalent to adjacent-chain factorization.

Claim boundary: `past`, `present`, and `future` are causal epochs.  They are not
three physical time dimensions, and this module asserts no empirical or
biological claim.
-/

namespace VFH2
namespace ThreeTime

/--
A deterministic structural model with three ordered causal epochs.

Finiteness is imposed by concrete benchmark instances, not required by the
generic semantic theorems below.
-/
structure DeterministicTriTemporalSCM where
  Past : Type
  Present : Type
  Future : Type
  presentLaw : Past → Present
  futureLaw : Past → Present → Future

/-- A complete state of a three-epoch structural model. -/
structure TriTemporalSCMState (model : DeterministicTriTemporalSCM) where
  past : model.Past
  present : model.Present
  future : model.Future

/-- The observational trajectory generated by an upstream past state. -/
def DeterministicTriTemporalSCM.realize
    (model : DeterministicTriTemporalSCM)
    (past : model.Past) : TriTemporalSCMState model where
  past := past
  present := model.presentLaw past
  future := model.futureLaw past (model.presentLaw past)

/-- Surgical intervention on the present mechanism, with downstream recomputation. -/
def DeterministicTriTemporalSCM.doPresent
    (model : DeterministicTriTemporalSCM)
    (past : model.Past)
    (present : model.Present) : TriTemporalSCMState model where
  past := past
  present := present
  future := model.futureLaw past present

/-- Surgical intervention on the terminal mechanism. -/
def DeterministicTriTemporalSCM.doFuture
    (model : DeterministicTriTemporalSCM)
    (past : model.Past)
    (future : model.Future) : TriTemporalSCMState model where
  past := past
  present := model.presentLaw past
  future := future

/-- The two downstream intervention forms in the minimal model. -/
inductive DownstreamIntervention (model : DeterministicTriTemporalSCM) where
  | setPresent : model.Present → DownstreamIntervention model
  | setFuture : model.Future → DownstreamIntervention model

/-- Apply a downstream intervention while retaining the supplied past state. -/
def DeterministicTriTemporalSCM.applyDownstream
    (model : DeterministicTriTemporalSCM)
    (past : model.Past) :
    DownstreamIntervention model → TriTemporalSCMState model
  | .setPresent present => model.doPresent past present
  | .setFuture future => model.doFuture past future

@[simp] theorem realize_past
    (model : DeterministicTriTemporalSCM)
    (past : model.Past) :
    (model.realize past).past = past := rfl

@[simp] theorem doPresent_past
    (model : DeterministicTriTemporalSCM)
    (past : model.Past)
    (present : model.Present) :
    (model.doPresent past present).past = past := rfl

@[simp] theorem doFuture_past
    (model : DeterministicTriTemporalSCM)
    (past : model.Past)
    (future : model.Future) :
    (model.doFuture past future).past = past := rfl

/--
No-retrocausality: neither supported downstream intervention rewrites the
upstream past component.
-/
theorem downstreamIntervention_preserves_past
    (model : DeterministicTriTemporalSCM)
    (past : model.Past)
    (intervention : DownstreamIntervention model) :
    (model.applyDownstream past intervention).past = past := by
  cases intervention <;> rfl

/-- A future-only intervention also preserves the generated present state. -/
@[simp] theorem doFuture_preserves_generated_present
    (model : DeterministicTriTemporalSCM)
    (past : model.Past)
    (future : model.Future) :
    (model.doFuture past future).present = model.presentLaw past := rfl

/-- Evidence is a predicate on complete three-epoch states. -/
abbrev TriTemporalEvidence (model : DeterministicTriTemporalSCM) : Type :=
  TriTemporalSCMState model → Prop

/-- Stronger evidence accepts no state rejected by weaker evidence. -/
def EvidenceRefines
    {model : DeterministicTriTemporalSCM}
    (stronger weaker : TriTemporalEvidence model) : Prop :=
  ∀ state, stronger state → weaker state

/-- Candidate pasts under fixed observed present/future values and evidence. -/
def CandidatePast
    {model : DeterministicTriTemporalSCM}
    (evidence : TriTemporalEvidence model)
    (present : model.Present)
    (future : model.Future)
    (past : model.Past) : Prop :=
  evidence { past := past, present := present, future := future }

/-- Stronger evidence can only remove candidate pasts. -/
theorem candidatePast_antitone_of_evidenceRefines
    {model : DeterministicTriTemporalSCM}
    {stronger weaker : TriTemporalEvidence model}
    (hrefines : EvidenceRefines stronger weaker)
    (present : model.Present)
    (future : model.Future)
    (past : model.Past)
    (hcandidate : CandidatePast stronger present future past) :
    CandidatePast weaker present future past :=
  hrefines _ hcandidate

/-- Strict shrinkage of the candidate-past projection. -/
def StrictCandidatePastRefinement
    {model : DeterministicTriTemporalSCM}
    (stronger weaker : TriTemporalEvidence model)
    (present : model.Present)
    (future : model.Future) : Prop :=
  (∀ past,
      CandidatePast stronger present future past →
        CandidatePast weaker present future past) ∧
    ∃ past,
      CandidatePast weaker present future past ∧
        ¬ CandidatePast stronger present future past

/-- A Boolean three-epoch SCM used only as a strict finite witness. -/
def booleanParitySCM : DeterministicTriTemporalSCM where
  Past := Bool
  Present := Bool
  Future := Bool
  presentLaw := fun past => past
  futureLaw
    | false, false => false
    | false, true => true
    | true, false => true
    | true, true => false

/-- Evidence imposing no additional constraint. -/
def unconstrainedBooleanEvidence : TriTemporalEvidence booleanParitySCM :=
  fun _ => True

/-- Existing even-parity geometry interpreted as evidence on complete states. -/
def evenParityEvidence : TriTemporalEvidence booleanParitySCM :=
  fun state => evenParity state.past state.present state.future

/-- Every observational state generated by the parity SCM satisfies its evidence law. -/
theorem booleanParitySCM_realize_satisfies_evenParity (past : Bool) :
    evenParityEvidence (booleanParitySCM.realize past) := by
  cases past <;> rfl

theorem evenParityEvidence_refines_unconstrained :
    EvidenceRefines evenParityEvidence unconstrainedBooleanEvidence := by
  intro state hstate
  trivial

/--
At observed present=false and future=false, refined parity evidence removes
the candidate past=true while retaining past=false.
-/
theorem evenParityEvidence_strict_candidatePast_refinement :
    StrictCandidatePastRefinement
      evenParityEvidence unconstrainedBooleanEvidence false false := by
  constructor
  · intro past hcandidate
    exact candidatePast_antitone_of_evidenceRefines
      evenParityEvidence_refines_unconstrained false false past hcandidate
  · refine ⟨true, ?_, ?_⟩
    · trivial
    · simp [CandidatePast, evenParityEvidence, evenParity]

/-- The actual past remains accepted after refinement. -/
theorem evenParityEvidence_retains_actualPast :
    CandidatePast evenParityEvidence false false false := by
  rfl

/--
Strict recontextualization without changing history: the same concrete state
retains its actual past while the set of compatible past explanations shrinks.
-/
theorem exists_strict_recontextualization_without_pastChange :
    ∃ actual : TriTemporalSCMState booleanParitySCM,
      actual.past = false ∧
        CandidatePast evenParityEvidence
          actual.present actual.future actual.past ∧
        StrictCandidatePastRefinement
          evenParityEvidence unconstrainedBooleanEvidence
          actual.present actual.future := by
  refine ⟨booleanParitySCM.realize false, rfl, ?_, ?_⟩
  · exact evenParityEvidence_retains_actualPast
  · exact evenParityEvidence_strict_candidatePast_refinement

/-- A Boolean-valued ternary test for executable rectangle defects. -/
abbrev BooleanTernaryConstraint (α : Type) : Type :=
  α → α → α → Bool

/-- Interpret a Boolean test as a propositional ternary relation. -/
def relationOfBooleanConstraint
    {α : Type}
    (r : BooleanTernaryConstraint α) : TernaryConstraint α :=
  fun past present future => r past present future = true

/--
One unit of defect exactly when two accepted rectangle corners have a rejected
mixed corner; zero otherwise.
-/
def naturalRectangleDefect
    {α : Type}
    (r : BooleanTernaryConstraint α)
    (pastOne pastTwo present futureOne futureTwo : α) : Nat :=
  if r pastOne present futureOne = true ∧
      r pastTwo present futureTwo = true ∧
      r pastOne present futureTwo = false then 1 else 0

/-- Zero local defect is exactly the local rectangle implication. -/
theorem naturalRectangleDefect_eq_zero_iff
    {α : Type}
    (r : BooleanTernaryConstraint α)
    (pastOne pastTwo present futureOne futureTwo : α) :
    naturalRectangleDefect r pastOne pastTwo present futureOne futureTwo = 0 ↔
      (r pastOne present futureOne = true →
        r pastTwo present futureTwo = true →
          r pastOne present futureTwo = true) := by
  unfold naturalRectangleDefect
  by_cases hFirst : r pastOne present futureOne = true
  · by_cases hSecond : r pastTwo present futureTwo = true
    · cases hMixed : r pastOne present futureTwo <;> simp_all
    · simp [hFirst, hSecond]
  · simp [hFirst]

/--
All computable rectangle defects vanish exactly when the induced relation
factors through an adjacent two-link chain.
-/
theorem relationOfBooleanConstraint_chainRepresentable_iff_all_defects_zero
    {α : Type}
    (r : BooleanTernaryConstraint α) :
    ChainRepresentable (relationOfBooleanConstraint r) ↔
      ∀ pastOne pastTwo present futureOne futureTwo,
        naturalRectangleDefect
          r pastOne pastTwo present futureOne futureTwo = 0 := by
  rw [chainRepresentable_iff_middleRectangleClosed]
  constructor
  · intro hrectangle pastOne pastTwo present futureOne futureTwo
    apply (naturalRectangleDefect_eq_zero_iff
      r pastOne pastTwo present futureOne futureTwo).2
    intro hFirst hSecond
    exact hrectangle pastOne pastTwo present futureOne futureTwo hFirst hSecond
  · intro hzero pastOne pastTwo present futureOne futureTwo hFirst hSecond
    exact (naturalRectangleDefect_eq_zero_iff
      r pastOne pastTwo present futureOne futureTwo).1
        (hzero pastOne pastTwo present futureOne futureTwo) hFirst hSecond

/-- A positive natural scale preserves the zero/nonzero defect classification. -/
def weightedNaturalRectangleDefect
    {α : Type}
    (weight : Nat)
    (r : BooleanTernaryConstraint α)
    (pastOne pastTwo present futureOne futureTwo : α) : Nat :=
  weight * naturalRectangleDefect
    r pastOne pastTwo present futureOne futureTwo

theorem relationOfBooleanConstraint_chainRepresentable_iff_all_weightedDefects_zero
    {α : Type}
    (weight : Nat)
    (hweight : 0 < weight)
    (r : BooleanTernaryConstraint α) :
    ChainRepresentable (relationOfBooleanConstraint r) ↔
      ∀ pastOne pastTwo present futureOne futureTwo,
        weightedNaturalRectangleDefect
          weight r pastOne pastTwo present futureOne futureTwo = 0 := by
  rw [relationOfBooleanConstraint_chainRepresentable_iff_all_defects_zero]
  constructor
  · intro hzero pastOne pastTwo present futureOne futureTwo
    simp [weightedNaturalRectangleDefect,
      hzero pastOne pastTwo present futureOne futureTwo]
  · intro hweighted pastOne pastTwo present futureOne futureTwo
    have hproduct := hweighted pastOne pastTwo present futureOne futureTwo
    unfold weightedNaturalRectangleDefect at hproduct
    rcases Nat.mul_eq_zero.mp hproduct with hweightZero | hdefectZero
    · omega
    · exact hdefectZero

/-- Executable Boolean form of the existing even-parity relation. -/
def evenParityBooleanConstraint : BooleanTernaryConstraint Bool
  | false, false, false => true
  | false, false, true => false
  | false, true, false => false
  | false, true, true => true
  | true, false, false => false
  | true, false, true => true
  | true, true, false => true
  | true, true, true => false

/--
The executable defect relation and the observer's parity evidence are the same
pointwise ternary geometry, not independent witnesses with similar names.
-/
theorem relationOfEvenParityBooleanConstraint_iff_evenParity
    (past present future : Bool) :
    relationOfBooleanConstraint evenParityBooleanConstraint
        past present future ↔
      evenParity past present future := by
  cases past <;> cases present <;> cases future <;>
    simp [relationOfBooleanConstraint, evenParityBooleanConstraint, evenParity]

/-- A concrete unit rectangle defect shared with the Python reference fixture. -/
theorem evenParityBooleanConstraint_defect_witness :
    naturalRectangleDefect
      evenParityBooleanConstraint false true false false true = 1 := by
  rfl

/-- The executable parity relation cannot factor through an adjacent chain. -/
theorem evenParityBooleanConstraint_not_chainRepresentable :
    ¬ ChainRepresentable
      (relationOfBooleanConstraint evenParityBooleanConstraint) := by
  intro hchain
  have hall :=
    (relationOfBooleanConstraint_chainRepresentable_iff_all_defects_zero
      evenParityBooleanConstraint).1 hchain
  have hzero := hall false true false false true
  rw [evenParityBooleanConstraint_defect_witness] at hzero
  omega

end ThreeTime
end VFH2
